Orientation
Thoronir42/kraz-huntley pull request #9
Opened 2020-08-28 22:28 UTC by only-a-ptr

2020-08-30 20:34 UTC, Thoronir42 requested changes
Díky za PR. Poprosím tě o dotažení pár maličkostí a pročištění komentářů, které jsem přidal ke kódu.

2020-08-30 20:34 UTC, Thoronir42 commented on DEVEL.txt
> +Treasure map of this "Treasure hunt app"
Přesuň, prosím, tenhle soubor do složky `/doc` ať nám nebobtná obsah kořene projektu.

2020-08-30 20:34 UTC, Thoronir42 commented on Modules/TreasureHunt/Components/RegisterFormFactory.php
> +        $form->addText('nick', 'Uživatel. jméno');
👍

Původní záměr byl vytvořit tématicky-pohlcující UX. Souhlasím s použitím tradičnějšího formuláře.

2020-08-30 20:34 UTC, Thoronir42 commented on Modules/TreasureHunt/Components/RegisterFormFactory.php
> +        $form['pass'] = new EmojiMatrixControl('Identifikátor (heslo)');
Řekl bych že bude lepší úplně vypustit slovo "Identifikátor" a nechat zde pouze "Heslo".

2020-08-30 20:34 UTC, Thoronir42 commented on Modules/TreasureHunt/Presenters/TreasureHuntPresenter.php
> +                if ($nick == "") {
Vyplnění hodnoty kontroluj validací v `CP\TreasureHunt\Components\RegisterFormFactory:13`

Například
```
$form->addText('nick', 'Jméno')
            ->setRequired()
            ->addRule(Form::MIN_LENGTH, "Jméno musí obsahovat alespoň 2 znaky", 2);
```

V tomto callbacku onSuccess by se už měly dít věci.

2020-08-30 20:34 UTC, Thoronir42 commented on Modules/TreasureHunt/Presenters/TreasureHuntPresenter.php
> +            // $values come in trimmed :)
Toto nemusí být vždy pravda - záleží na konkrétních formulářových prvcích a případně jejich nastavení

Komentář nic nepřináší, odeber ho prosím

2020-08-30 20:34 UTC, Thoronir42 commented on Modules/TreasureHunt/Presenters/TreasureHuntPresenter.php
> +                    $this->flashMessage("Pro registraci zadejte uživatel. jméno");
Uvědomil jsem si, že formuláře umí zobrazovat chyby a tedy bychom se mohli prozatím vyhnout flash zprávám mimo komponenty.

Můžeš prosím změnit použití `$this->flashMessage('...')` na `$form->addError('...', false)`?

2020-08-30 20:34 UTC, Thoronir42 commented on Modules/TreasureHunt/templates/TreasureHunt/intro.latte
> +<h1>Vítejte ve hře o poklad.</h1>
Úvod stručně a k věci. 👍 :)

2020-08-30 20:34 UTC, Thoronir42 commented on Modules/TreasureHunt/templates/TreasureHunt/intro.latte
> +<pre>~~Šablona: /Modules/TreasureHunt/templates/TreasureHunt/intro.latte~~</pre>
Odeber odsud, prosím, výpis souboru šablony.

Uvítal bys kdyby se dalo na každém pohledu zobrazit, jaký soubor šablony je zrovna použit v podobě panelu v liště Tracy?

2020-09-01 06:21 UTC, po185021 commented on Modules/TreasureHunt/Presenters/TreasureHuntPresenter.php
> +                if ($nick == "") {
za tu dobu nez jsi napsal tento komentar uz jsi to mohl opravit sam v masteru a rict mi at tenhle commit vyradim.

2020-09-01 06:27 UTC, only-a-ptr commented
Prosimte, tahle cela branch je jen muj pruzkum jestli to budu schopen dokoncit bez tebe. Nevedel jsem jestlis to neopustil.

Cherrypickni co ti pripada pouzitelne a zbytek zahod. Neztracej cas psanim profesionalne formulovanych komentaru.

2020-09-01 19:37 UTC, closed without merging